In [ ]:
### Q 1 extract odd numbers from arr
import numpy as np

In [ ]:
arr=np.array([0,1,2,3,4,6,7,8,9])

In [ ]:
arr[arr%2==1]

array([1, 3, 7, 9])

In [ ]:
### Q 2 replace all odd number with -1
arr=np.array([0,1,2,3,4,6,7,8,9])
arr[arr%2==1]
arr[arr%2==1]= -1

In [ ]:
arr

array([ 0, -1,  2, -1,  4,  6, -1,  8, -1])

In [ ]:
### Q 3 convert 1D array to 2D array with two rows
a=np.array([0,1,2,3,4,5,6,7,8,9])
new=a.reshape(2,5)

In [ ]:
new

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
### Q 4 create a pattern using numpy functions
a=np.array([1,2,3])

In [ ]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
### Q 5 get the common items between a & b
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])


In [ ]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [ ]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [ ]:
print(np.intersect1d(a, b))

[2 4]


In [ ]:
###  Que 6
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Remove = np.setdiff1d(a, b)
print(Remove)

[1 2 3 4]


In [8]:
### Q 7
import numpy as np
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [9]:
(arr[:, None] == np.unique(arr)).view(np.int8)



array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

### Q 8  Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
import numpy as np

In [ ]:
np.arange(5,34,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])